# Testbench配置文件 (YAML格式)
# 包含EDA工具、模型、分析、激励、变量、输出、初始条件和后处理信息

# 模型文件配置
models:
  files:
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "tt",
      ] # [模型文件路径, 工艺角]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "res_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "dio_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "bjt_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "mim_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "var_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_spe.lib",
        "mom_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_v2p6_7p_res_spe.ckt",
        "",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "mos_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "mim_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "res_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "mom_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "var_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "spirind_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "diffind_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "3tdiffind_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "rf_ind_spi_mf_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "rf_ind_spi_mf_psub_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "rf_3Tdiff_1talpa_tt",
      ]
    - [
        "/home/IC/Tech/PDK_13mmrf_1P6M_30k/models/spectre/ms013_io33_rf_v1p9_spe.lib",
        "rf_3Tdiff_1talpa_psub_tt",
      ]

# 分析配置
analyses:
  # 瞬态分析
  tran:
    start: "0"
    stop: "10u" # 仿真停止时间
    step: "10n" # 仿真步长
    errpreset: "conservative" # 高精度

  # DC分析
  dc:
    saveOppoint: "t" # 保存工作点
    param1: "vin" # 扫描参数1
    start1: 0 # 起始值
    stop1: 1.8 # 结束值
    step1: 0.1 # 步长

  # AC分析
  ac:
    start: "1" # 起始频率
    stop: "1G" # 结束频率
    dec: 10 # 每十倍频程点数

# 激励文件配置
stimulus:
  files: [] # 空数组，跳过激励文件验证

# 环境配置
environment:
  temperature: 27.0 # 仿真温度 (摄氏度)
  supply_voltage: 1.8 # 电源电压 (V)

# 设计变量
variables:
  vdd: 1.8 # 电源电压
  vth: 0.4 # 阈值电压
  temperature_coeff: 1e-3 # 温度系数
  load_cap: 100e-15 # 负载电容 (F)
  bias_current: 10e-6 # 偏置电流 (A)

# 输出配置
outputs:
  save_nodes: # 需要保存的节点
    - "/vout" # 输出电压
    - "/vin" # 输入电压
    - "/vdd" # 电源电压
    - "/vss" # 地电压
    - "/ibias" # 偏置电流

# 初始条件
initial_conditions:
  "/vout": 0.9 # 输出节点初始电压
  "/vin": 0.0 # 输入节点初始电压

# 后处理配置
post_processing:
  plot_enabled: true # 是否启用绘图
  save_data: true # 是否保存数据文件

  plots: # 绘图配置
    - data: 'v("/vout")'
      xlabel: "时间 (s)"
      ylabel: "电压 (V)"
    - data: 'v("/vin")'
      xlabel: "时间 (s)"
      ylabel: "电压 (V)"

  save_items: # 数据保存配置
    - file: "vout_data.csv"
      data: 'v("/vout")'
    - file: "vin_data.csv"
      data: 'v("/vin")'
