# 系统配置文件 (YAML格式)
# 包含服务器配置信息，程序启动时加载到内存作为全局变量

server:
  url: "http://localhost:8080" # 项目管理服务器URL
  api_key: "" # API密钥

# EDA工具配置
eda_tools:
  # Cadence Virtuoso工具配置
  virtuoso:
    # 启动命令配置
    executable: "virtuoso" # 主执行命令
    launch_args: ["-nograph"] # 启动参数

    # Virtuoso所需的所有环境变量
    environment_variables:
      [
        "export CADHOME=/opt/cadence",
        "export LANG=C",
        "export CDS_Netlisting_Mode=Analog",
        "export CDS_LOAD_ENV=CWD",
        "export CDS=$CADHOME/IC617",
        "export CDSDIR=$CDS",
        "export CDSHOME=$CDS",
        "export CADENCE_DIR=$CDS",
        "export CDS_INST_DIR=$CDS",
        "export CDS_ROOT=$CDS",
        "export CDSROOT=$CDS",
        "export CDS_LIC_FILE=$CDS/share/license/license.dat",
        "export CDS_LIC_ONLY=1",
        "export CDS_AUTO_64BIT=ALL",
        "export PATH=$PATH:$CDSDIR/tools/dfII/bin:$CDSDIR/tools/plot/bin",
        "export CDS_ENABLE_VMS=1",
        "export MMSIMHOME=$CADHOME/MMSIM151",
        "export PATH=$PATH:$MMSIMHOME/bin:$MMSIMHOME/tools/relxpert/bin",
        "export SYSTEM_CDS_LIB_DIR=/opt/cadence/IC617/share/cdssetup",
      ]

    # 仿真器特定选项
    options:
      gui_mode: false # 是否启用GUI模式
      skill_path: "/opt/cadence/skill" # 自定义SKILL路径
      layout_editor: true # 是否支持版图编辑
      schematic_editor: true # 是否支持原理图编辑

  # Cadence Spectre工具配置
  spectre:
    # 启动命令配置
    executable: "spectre" # 主执行命令
    launch_args: ["-nograph", "-replay"] # 启动参数

    # Spectre所需的所有环境变量
    environment_variables:
      [
        "export CADHOME=/opt/cadence",
        "export ALTOSHOME=$CADHOME/LIBERATE151",
        "export PATH=$PATH:$ALTOSHOME/bin",
        "export PATH=$PATH:$ALTOSHOME/tools.lnx86/spectre/bin",
        "export ALTOS_64=1",
        "export CDS_LIC_FILE=$CDS/share/license/license.dat",
      ]

    # 仿真器特定选项
    options:
      default_precision: "moderate" # 默认仿真精度
      max_memory: "8G" # 最大内存使用
      num_threads: 4 # 并行线程数
